/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diary_exporter;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Darina
 */
public class NewJFrame extends javax.swing.JFrame {    
    public NewJFrame() {
        initComponents();                                             
        check_old_img_set_visibility();
        this.setVisible(true);
    }
    
    public void printInfo(Object o) {
        label_rezult.setText(o.toString());
    }
    public void printErrorInfo(int i) {
        switch(i) {
            case -1:
                errorText.setText("Не удалось создать лог-файл");
                errorText.setVisible(true);
                break;
            case 0:
                errorText.setText("diary не ответил на запрос. Попробуйте перезапустить программу еще раз позже.");
                errorText.setVisible(true);
                break;
            case 1:
                errorText.setText("В старых файлах нет поля хэша. Лучше выкачайте их заново.");
                errorText.setVisible(true);
                break;
            case 2:
                errorText.setText("Во время выкачки произошли ошибки. Вы можете отправить отчет в группу вконтакте vk.com/aboutdybr или на почту support@dybr.ru\nФайл отчета diary_exporter_log_file.log");
                errorText.setVisible(true);
                break;
        }
        
    }
    
    public String getLogin() {
        return text_login.getText();
    }
    public String getPass() {
        return text_pass.getText();
    }
    public String getDir() {
        return text_dir.getText();
    }
    
    public boolean addLoad() {
        return check_add.isSelected();
    }
    public boolean loadImage() {
        return check_img.isSelected();
    }
    public boolean checkLoaded() {
        return check_old_img.isSelected();
    }
    
    public void changeEnabled() {
        boolean e = !button_start.isEnabled();
        text_login.setEnabled(e);
        text_pass.setEnabled(e);
        text_dir.setEnabled(e);
        check_add.setEnabled(e);
        check_img.setEnabled(e);
        button_dir.setEnabled(e);
        button_start.setEnabled(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_dir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        button_dir = new javax.swing.JButton();
        button_start = new javax.swing.JButton();
        check_add = new javax.swing.JCheckBox();
        check_img = new javax.swing.JCheckBox();
        label_rezult = new javax.swing.JLabel();
        check_old_img = new javax.swing.JCheckBox();
        text_pass = new javax.swing.JPasswordField();
        errorText = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(394, 498));
        setMinimumSize(new java.awt.Dimension(394, 498));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("<html>\nКОМАНДА ДЫБРА ПРИВЕТСТВУЕТ ВАС!\n<br>\n<br>Пожалуйста, введите данные своей учетной записи.\n<br>Пароль необходим для выгрузки дневника и не будет записан где-либо.");
        jLabel1.setFocusable(false);

        jLabel2.setText("логин:");
        jLabel2.setFocusable(false);

        jLabel3.setText("пароль:");
        jLabel3.setFocusable(false);

        jLabel4.setText("Директория:");
        jLabel4.setFocusable(false);

        button_dir.setText("...");
        button_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dirActionPerformed(evt);
            }
        });

        button_start.setText("Начать");
        button_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_startActionPerformed(evt);
            }
        });

        check_add.setText("дополнить существующие файлы");
        check_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_addActionPerformed(evt);
            }
        });

        check_img.setText("выгрузить изображения");
        check_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_imgActionPerformed(evt);
            }
        });

        label_rezult.setBackground(new java.awt.Color(0, 51, 51));
        label_rezult.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_rezult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_rezult.setFocusable(false);

        check_old_img.setText("в том числе из загруженных ранее записей");

        errorText.setEditable(false);
        errorText.setBackground(java.awt.SystemColor.control);
        errorText.setColumns(20);
        errorText.setForeground(new java.awt.Color(153, 0, 0));
        errorText.setLineWrap(true);
        errorText.setRows(5);
        errorText.setWrapStyleWord(true);
        errorText.setAlignmentX(0.0F);
        errorText.setAlignmentY(0.0F);
        errorText.setAutoscrolls(false);
        errorText.setBorder(null);
        errorText.setCaretColor(java.awt.SystemColor.window);
        errorText.setMargin(new java.awt.Insets(0, 0, 0, 0));
        errorText.setMaximumSize(new java.awt.Dimension(0, 0));
        errorText.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_rezult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(check_img)
                                .addComponent(check_add)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(text_dir)
                                    .addGap(18, 18, 18)
                                    .addComponent(button_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text_login)
                                        .addComponent(text_pass))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(check_old_img))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_start)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_dir))
                .addGap(18, 18, 18)
                .addComponent(check_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_img)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_old_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_start, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(label_rezult, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.getAccessibleContext().setAccessibleName("КОМАНДА ДЫБРА ПРИВЕТСТВУЕТ ВАС!\n\nПожалуйста, введите данные своей учетной записи.\nПароль необходим для выгрузки дневника и не будет записан где-либо.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dirActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Choose parent directory:");
        fc.setCurrentDirectory(new File(""));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            text_dir.setText(fc.getSelectedFile().toString());
            }
    }//GEN-LAST:event_button_dirActionPerformed

    private void button_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_startActionPerformed
        label_rezult.setText("");
        errorText.setText("");
        errorText.setVisible(false);
        changeEnabled();
        new Thread(new Diary_exporter(this)).start();
    }//GEN-LAST:event_button_startActionPerformed

    private void check_old_img_set_visibility() {
        if(check_add.isSelected() && check_img.isSelected()) {
            check_old_img.setEnabled(true);
        } else {
            check_old_img.setEnabled(false);
        }
    }
    
    private void check_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_addActionPerformed
        check_old_img_set_visibility();
    }//GEN-LAST:event_check_addActionPerformed

    private void check_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_imgActionPerformed
        check_old_img_set_visibility();
    }//GEN-LAST:event_check_imgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_dir;
    private javax.swing.JButton button_start;
    private javax.swing.JCheckBox check_add;
    private javax.swing.JCheckBox check_img;
    private javax.swing.JCheckBox check_old_img;
    private javax.swing.JTextArea errorText;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_rezult;
    private javax.swing.JTextField text_dir;
    private javax.swing.JTextField text_login;
    private javax.swing.JPasswordField text_pass;
    // End of variables declaration//GEN-END:variables
}
